### ISSUE TITLE
cn localization for 1.3.1

### ISSUE THREAD

**Issue by Kifusou** [Llisandur/MythicArcanist#3]
Simply trans to chinese base on the LocalizationPack.json file.
Don't know anything about code or github, so what i can do is just put the file here.
Thank you for your mod!love it.
[LocalizationPack.zip](https://github.com/Llisandur/MythicArcanist/files/10094067/LocalizationPack.zip)

**Comment by Llisandur** [comment]
Commit [3392845](https://github.com/Llisandur/MythicArcanist/commit/3392845e7e2a73350a6b99fff681a0f52c1fb0d2) for version 1.3.2
