### ISSUE TITLE
Two-Weapon Warrior archetype is broken in new update

### ISSUE THREAD

**Issue by tomek** [Llisandur/MythicArcanist#8]
What the title says, 2.1 update broke this archetype, character get no bonuses for wielding two weapons nor abilities work - when using Dualstrike character moves to enemy, there is attack animation but nothing happens.

PS. AFAIK other stuff from mod works (like spells and mythic arcanist abilities)

**Comment by Llisandur** [comment]
I've managed to fix Doublestrike, I'm just checking all the other abilities work before releasing a new version. Twin Blades says it only works when making a full attack, so you won't see the bonus with Doublestrike.

**Comment by Llisandur** [comment]
Release has been added.

**Comment by tomek** [comment]
Great, thank you.
